using MPMAR.Data;
using MPMAR.Data.Enums;
using MPMAR.Web.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MPMAR.Web.Admin.Mappers
{
    public static class CityPlanMapper
    {
        public static CityPlanVersion MapToCityPlanVersion(this CityPlanEditViewModel cityPlan)
        {
            var ctPlan = new CityPlanVersion()
            {
                Id = cityPlan.Id,
                ModificationDate = cityPlan.ModificationDate,
                VersionStatusEnum = cityPlan.VersionStatusEnum,
                IsDeleted = cityPlan.IsDeleted,
                ChangeActionEnum = cityPlan.ChangeActionEnum,
                CityPlanId = cityPlan.CityPlanId,
                ModifiedById = cityPlan.ModifiedById,
                CreationDate = cityPlan.CreationDate,
                CreatedById = cityPlan.CreatedById,
                ApprovalDate = cityPlan.ApprovalDate,
                ApprovedById = cityPlan.ApprovedById,
                IsActive = cityPlan.IsActive,
                EnPageDescription = cityPlan.EnPageDescription,
                ArPageDescription = cityPlan.ArPageDescription,
                EnAlexandria = cityPlan.EnAlexandria,
                ArAlexandria = cityPlan.ArAlexandria,
                EnAswan = cityPlan.EnAswan,
                ArAswan = cityPlan.ArAswan,
                EnAsyut = cityPlan.EnAsyut,
                ArAsyut = cityPlan.ArAsyut,
                EnBeheira = cityPlan.EnBeheira,
                ArBeheira = cityPlan.ArBeheira,
                EnBeniSuef = cityPlan.EnBeniSuef,
                ArBeniSuef = cityPlan.ArBeniSuef,
                EnCairo = cityPlan.EnCairo,
                ArCairo = cityPlan.ArCairo,
                EnDakahlia = cityPlan.EnDakahlia,
                ArDakahlia = cityPlan.ArDakahlia,
                EnDamietta = cityPlan.EnDamietta,
                ArDamietta = cityPlan.ArDamietta,
                EnFaiyum = cityPlan.EnFaiyum,
                ArFaiyum = cityPlan.ArFaiyum,
                EnGharbia = cityPlan.EnGharbia,
                ArGharbia = cityPlan.ArGharbia,
                EnGiza = cityPlan.EnGiza,
                ArGiza = cityPlan.ArGiza,
                EnIsmailia = cityPlan.EnIsmailia,
                ArIsmailia = cityPlan.ArIsmailia,
                EnKafrElSheikh = cityPlan.EnKafrElSheikh,
                ArKafrElSheikh = cityPlan.ArKafrElSheikh,
                EnLuxor = cityPlan.EnLuxor,
                ArLuxor = cityPlan.ArLuxor,
                EnMatruh = cityPlan.EnMatruh,
                ArMatruh = cityPlan.ArMatruh,
                EnMinya = cityPlan.EnMinya,
                ArMinya = cityPlan.ArMinya,
                EnMonufia = cityPlan.EnMonufia,
                ArMonufia = cityPlan.ArMonufia,
                EnNewValley = cityPlan.EnNewValley,
                ArNewValley = cityPlan.ArNewValley,
                EnNorthSinai = cityPlan.EnNorthSinai,
                ArNorthSinai = cityPlan.ArNorthSinai,
                EnPortSaid = cityPlan.EnPortSaid,
                ArPortSaid = cityPlan.ArPortSaid,
                EnQalyubia = cityPlan.EnQalyubia,
                ArQalyubia = cityPlan.ArQalyubia,
                EnQena = cityPlan.EnQena,
                ArQena = cityPlan.ArQena,
                EnRedSea = cityPlan.EnRedSea,
                ArRedSea = cityPlan.ArRedSea,
                EnSharqia = cityPlan.EnSharqia,
                ArSharqia = cityPlan.ArSharqia,
                EnSohag = cityPlan.EnSohag,
                ArSohag = cityPlan.ArSohag,
                EnSouthSinai = cityPlan.EnSouthSinai,
                ArSouthSinai = cityPlan.ArSouthSinai,
                EnSuez = cityPlan.EnSuez,
                ArSuez = cityPlan.ArSuez,
            };

            return ctPlan;
        }


        public static CityPlanEditViewModel MapToCityPlanViewModel(this CityPlan cityPlan)
        {
            var ctPlan = new CityPlanEditViewModel()
            {
                Id = 0,
                ModificationDate = cityPlan.ModificationDate,
                VersionStatusEnum = VersionStatusEnum.Draft,
                IsDeleted = cityPlan.IsDeleted,
                ChangeActionEnum = ChangeActionEnum.New,
                CityPlanId = cityPlan.Id,
                ModifiedById = cityPlan.ModifiedById,
                CreationDate = cityPlan.CreationDate,
                CreatedById = cityPlan.CreatedById,
                ApprovalDate = cityPlan.ApprovalDate,
                ApprovedById = cityPlan.ApprovedById,
                IsActive = cityPlan.IsActive,
                EnPageDescription = cityPlan.EnPageDescription,
                ArPageDescription = cityPlan.ArPageDescription,
                EnAlexandria = cityPlan.EnAlexandria,
                ArAlexandria = cityPlan.ArAlexandria,
                EnAswan = cityPlan.EnAswan,
                ArAswan = cityPlan.ArAswan,
                EnAsyut = cityPlan.EnAsyut,
                ArAsyut = cityPlan.ArAsyut,
                EnBeheira = cityPlan.EnBeheira,
                ArBeheira = cityPlan.ArBeheira,
                EnBeniSuef = cityPlan.EnBeniSuef,
                ArBeniSuef = cityPlan.ArBeniSuef,
                EnCairo = cityPlan.EnCairo,
                ArCairo = cityPlan.ArCairo,
                EnDakahlia = cityPlan.EnDakahlia,
                ArDakahlia = cityPlan.ArDakahlia,
                EnDamietta = cityPlan.EnDamietta,
                ArDamietta = cityPlan.ArDamietta,
                EnFaiyum = cityPlan.EnFaiyum,
                ArFaiyum = cityPlan.ArFaiyum,
                EnGharbia = cityPlan.EnGharbia,
                ArGharbia = cityPlan.ArGharbia,
                EnGiza = cityPlan.EnGiza,
                ArGiza = cityPlan.ArGiza,
                EnIsmailia = cityPlan.EnIsmailia,
                ArIsmailia = cityPlan.ArIsmailia,
                EnKafrElSheikh = cityPlan.EnKafrElSheikh,
                ArKafrElSheikh = cityPlan.ArKafrElSheikh,
                EnLuxor = cityPlan.EnLuxor,
                ArLuxor = cityPlan.ArLuxor,
                EnMatruh = cityPlan.EnMatruh,
                ArMatruh = cityPlan.ArMatruh,
                EnMinya = cityPlan.EnMinya,
                ArMinya = cityPlan.ArMinya,
                EnMonufia = cityPlan.EnMonufia,
                ArMonufia = cityPlan.ArMonufia,
                EnNewValley = cityPlan.EnNewValley,
                ArNewValley = cityPlan.ArNewValley,
                EnNorthSinai = cityPlan.EnNorthSinai,
                ArNorthSinai = cityPlan.ArNorthSinai,
                EnPortSaid = cityPlan.EnPortSaid,
                ArPortSaid = cityPlan.ArPortSaid,
                EnQalyubia = cityPlan.EnQalyubia,
                ArQalyubia = cityPlan.ArQalyubia,
                EnQena = cityPlan.EnQena,
                ArQena = cityPlan.ArQena,
                EnRedSea = cityPlan.EnRedSea,
                ArRedSea = cityPlan.ArRedSea,
                EnSharqia = cityPlan.EnSharqia,
                ArSharqia = cityPlan.ArSharqia,
                EnSohag = cityPlan.EnSohag,
                ArSohag = cityPlan.ArSohag,
                EnSouthSinai = cityPlan.EnSouthSinai,
                ArSouthSinai = cityPlan.ArSouthSinai,
                EnSuez = cityPlan.EnSuez,
                ArSuez = cityPlan.ArSuez,
            };

            return ctPlan;
        }


        public static CityPlanEditViewModel MapToCityPlanViewModel(this CityPlanVersion cityPlan)
        {
            var ctPlan = new CityPlanEditViewModel()
            {
                Id = cityPlan.Id,
                ModificationDate = cityPlan.ModificationDate,
                VersionStatusEnum = cityPlan.VersionStatusEnum,
                IsDeleted = cityPlan.IsDeleted,
                ChangeActionEnum = cityPlan.ChangeActionEnum,
                CityPlanId = cityPlan.CityPlanId,
                ModifiedById = cityPlan.ModifiedById,
                CreationDate = cityPlan.CreationDate,
                CreatedById = cityPlan.CreatedById,
                ApprovalDate = cityPlan.ApprovalDate,
                ApprovedById = cityPlan.ApprovedById,
                IsActive = cityPlan.IsActive,
                EnPageDescription = cityPlan.EnPageDescription,
                ArPageDescription = cityPlan.ArPageDescription,
                EnAlexandria = cityPlan.EnAlexandria,
                ArAlexandria = cityPlan.ArAlexandria,
                EnAswan = cityPlan.EnAswan,
                ArAswan = cityPlan.ArAswan,
                EnAsyut = cityPlan.EnAsyut,
                ArAsyut = cityPlan.ArAsyut,
                EnBeheira = cityPlan.EnBeheira,
                ArBeheira = cityPlan.ArBeheira,
                EnBeniSuef = cityPlan.EnBeniSuef,
                ArBeniSuef = cityPlan.ArBeniSuef,
                EnCairo = cityPlan.EnCairo,
                ArCairo = cityPlan.ArCairo,
                EnDakahlia = cityPlan.EnDakahlia,
                ArDakahlia = cityPlan.ArDakahlia,
                EnDamietta = cityPlan.EnDamietta,
                ArDamietta = cityPlan.ArDamietta,
                EnFaiyum = cityPlan.EnFaiyum,
                ArFaiyum = cityPlan.ArFaiyum,
                EnGharbia = cityPlan.EnGharbia,
                ArGharbia = cityPlan.ArGharbia,
                EnGiza = cityPlan.EnGiza,
                ArGiza = cityPlan.ArGiza,
                EnIsmailia = cityPlan.EnIsmailia,
                ArIsmailia = cityPlan.ArIsmailia,
                EnKafrElSheikh = cityPlan.EnKafrElSheikh,
                ArKafrElSheikh = cityPlan.ArKafrElSheikh,
                EnLuxor = cityPlan.EnLuxor,
                ArLuxor = cityPlan.ArLuxor,
                EnMatruh = cityPlan.EnMatruh,
                ArMatruh = cityPlan.ArMatruh,
                EnMinya = cityPlan.EnMinya,
                ArMinya = cityPlan.ArMinya,
                EnMonufia = cityPlan.EnMonufia,
                ArMonufia = cityPlan.ArMonufia,
                EnNewValley = cityPlan.EnNewValley,
                ArNewValley = cityPlan.ArNewValley,
                EnNorthSinai = cityPlan.EnNorthSinai,
                ArNorthSinai = cityPlan.ArNorthSinai,
                EnPortSaid = cityPlan.EnPortSaid,
                ArPortSaid = cityPlan.ArPortSaid,
                EnQalyubia = cityPlan.EnQalyubia,
                ArQalyubia = cityPlan.ArQalyubia,
                EnQena = cityPlan.EnQena,
                ArQena = cityPlan.ArQena,
                EnRedSea = cityPlan.EnRedSea,
                ArRedSea = cityPlan.ArRedSea,
                EnSharqia = cityPlan.EnSharqia,
                ArSharqia = cityPlan.ArSharqia,
                EnSohag = cityPlan.EnSohag,
                ArSohag = cityPlan.ArSohag,
                EnSouthSinai = cityPlan.EnSouthSinai,
                ArSouthSinai = cityPlan.ArSouthSinai,
                EnSuez = cityPlan.EnSuez,
                ArSuez = cityPlan.ArSuez,
            };

            return ctPlan;
        }


    }
}

